FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && apt-get install -y \
    build-essential \
    gdb \
    make \
    cmake \
    pkg-config \
    git \
    libsfml-dev \
    xvfb \
    && apt-get clean